name: Weather

on:
  push:
    branches: [ main, master ]

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: weather-app
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker tag $REGISTRY/$IMAGE_NAME:${{ github.sha }} $REGISTRY/$IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Install dependencies
        run: npm install

      - name: Run unit test
        env:
          API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node test.js

      - name: Pull latest image
        if: ${{ success() }}
        run: docker compose pull

      - name: Docker Run
        if: ${{ success() }}
        run: |
          docker compose up --build -d

      - name: Show container logs
        if: ${{ success() }}
        run: |
          docker compose logs app --tail=50
